
export const KEY_PRESS_EVENT = "KEY_PRESS_EVENT"
export const BUTTON_CLICK_EVENT = "BUTTON_CLICK_EVENT"
export const INPUT_PASSED_EVENT = "INPUT_PASSED_EVENT"

export const ORDER_CREATED = "ORDER_CREATED"
export const ORDER_ALLOCATED = "ORDER_ALLOCATED"
export const ORDER_STARTED = "ORDER_STARTED"
export const ORDER_COMPLETED = "ORDER_COMPLETED"