name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build latest Docker image
      run: docker build . --file Standalone.Dockerfile --tag saumyabhatt10642/ese-client

    - name: Push the latest image to DockerHub
      run: docker push saumyabhatt10642/ese-client

    - name: Build Simulate Docker image
      run: docker build . --file Simulate.Dockerfile --tag saumyabhatt10642/ese-client:simulate

    - name: Push the simulate image to DockerHub
      run: docker push saumyabhatt10642/ese-client:simulate
