name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCEKR_PASSWORD

    - name: Build latest Docker image
      run: docker build . --file Dockerfile --tag saumyabhatt10642/ese-client

    - name: Push the latest image to DockerHub
      run: docker push saumyabhatt10642/ese-client
    
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          
    - name: Merge master back to simulate
      run: |
          git fetch --unshallow
          git checkout simulate
          git pull
          git merge --no-ff master -m "Auto-merge master back to simulate"
          git push

    - name: Build Simulate Docker image
      run: docker build . --file Dockerfile --tag saumyabhatt10642/ese-client:simulate

    - name: Push the simulate image to DockerHub
      run: docker push saumyabhatt10642/ese-client:simulate
